# Generated by Django 3.0.8 on 2020-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000, null=True)),
                ('tier', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('auctioneer', models.CharField(max_length=128, null=True)),
                ('starting_bid', models.FloatField()),
                ('count', models.IntegerField()),
                ('username', models.CharField(max_length=32, null=True)),
                ('start', models.CharField(max_length=50, null=True)),
                ('end', models.CharField(max_length=50, null=True)),
                ('bin', models.BooleanField(default=False, null=True)),
                ('uuid', models.CharField(max_length=128, null=True)),
                ('item_bytes', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
