# Generated by Django 3.0.8 on 2020-07-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='id',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='uuid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
