# Generated by Django 3.0.8 on 2020-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouse', '0002_auto_20200721_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auctioneer',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='bin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_bytes',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='item_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='start',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='tier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
