# Generated by Django 3.0.8 on 2020-07-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouse', '0003_auto_20200721_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='uuid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
