# Generated by Django 3.0.8 on 2020-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discordID',
            field=models.CharField(blank=True, max_length=255, verbose_name='discordID'),
        ),
    ]
