# Generated by Django 3.0.8 on 2020-07-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BazaarBuySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=1000, null=True)),
                ('amount', models.IntegerField()),
                ('pricePerUnit', models.FloatField()),
                ('orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BazaarQuickStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=1000, null=True)),
                ('sellPrice', models.FloatField()),
                ('sellVolume', models.IntegerField()),
                ('sellMovingWeek', models.IntegerField()),
                ('sellOrders', models.IntegerField()),
                ('buyPrice', models.FloatField()),
                ('buyVolume', models.IntegerField()),
                ('buyMovingWeek', models.IntegerField()),
                ('buyOrders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BazaarSellSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=1000, null=True)),
                ('amount', models.IntegerField()),
                ('pricePerUnit', models.FloatField()),
                ('orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BazaarListing',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('buy_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazaar.BazaarBuySummary')),
                ('quick_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazaar.BazaarQuickStatus')),
                ('sell_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazaar.BazaarSellSummary')),
            ],
            options={
                'ordering': ['id', 'buy_summary', 'sell_summary', 'quick_status'],
            },
        ),
    ]
