# Generated by Django 3.0.8 on 2020-07-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaarlisting',
            name='buy_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.BazaarBuySummary'),
        ),
        migrations.AlterField(
            model_name='bazaarlisting',
            name='sell_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.BazaarSellSummary'),
        ),
    ]
